export const STORAGE_KEY = "home-fall-map-v3";
export const DEX_SIZE = 16;

export const PETS = [
  { id: "jibyojeong", name: "집요정", file: "pet-jibyojeong.png", starter: true },
  { id: "nabi", name: "나비", file: "pet-nabi.png", starter: true },
  { id: "bori", name: "보리", file: "pet-bori.png", starter: true },
  { id: "haneul", name: "하늘이", file: "pet-haneul.png" },
  { id: "laben", name: "노을이", file: "pet-laben.png" },
  { id: "haetsal", name: "햇살이", file: "pet-haetsal.png" },
  { id: "iseul", name: "이슬이", file: "pet-iseul.png" },
  { id: "milky", name: "밀키", file: "pet-milky.png" },
  { id: "momo", name: "모모", file: "pet-momo.png" },
  { id: "yeontan", name: "연탄", file: "pet-yeontan.png" },
  { id: "dalnyang", name: "달냥", file: "pet-dalnyang.png" },
  { id: "mungchi", name: "뭉치", file: "pet-mungchi.png" },
  { id: "kong", name: "콩이", file: "pet-kong.png" },
  { id: "som", name: "솜이", file: "pet-som.png" },
  { id: "cookie", name: "쿠키", file: "pet-cookie.png" },
  { id: "coco", name: "코코", file: "pet-coco.png" },
];

export const ZONES = [
  {
    id: "living",
    name: "거실",
    mission: "거실 탐험",
    stamp: "거실 도장",
    emoji: "🛋️",
    pet: "소파에서 화장실·현관으로 가는 길을 같이 살펴봐요.",
  },
  {
    id: "bath",
    name: "화장실",
    mission: "화장실 탐험",
    stamp: "화장실 도장",
    emoji: "🚿",
    pet: "물기와 문턱, 잡을 곳을 천천히 확인해 주세요.",
  },
  {
    id: "kitchen",
    name: "부엌",
    mission: "부엌 탐험",
    stamp: "부엌 도장",
    emoji: "🍳",
    pet: "자주 쓰는 물건과 바닥이 미끄러운지 함께 봐요.",
  },
  {
    id: "bedroom",
    name: "침실",
    mission: "침실 탐험",
    stamp: "침실 도장",
    emoji: "🛏️",
    pet: "침대 옆 물건과 조명을 같이 확인해 봐요.",
  },
  {
    id: "path",
    name: "침실-화장실 경로",
    shortName: "이동 경로",
    mission: "밤길 탐험",
    stamp: "밤길 도장",
    emoji: "🌙",
    pet: "밤에 침실에서 화장실까지 걸어가는 길을 떠올려 보세요.",
  },
  {
    id: "entrance",
    name: "현관",
    mission: "현관 탐험",
    stamp: "현관 도장",
    emoji: "🚪",
    pet: "신발을 신고 벗는 자리와 단차를 살펴봐요.",
  },
];

export const QUESTIONS = [
  {
    id: "living-mat",
    zoneId: "living",
    text: "거실의 러그·카펫·전기매트·발매트가 밀리거나 가장자리가 들떠 있나요?",
    finding: "거실 매트가 밀리거나 가장자리가 들떠 있어요.",
    action: "사용하지 않는 매트는 치운다. 매트는 밑바닥이 고정되도록 미끄럼 방지 스티커를 붙인다.",
    urgent: false,
  },
  {
    id: "living-path",
    zoneId: "living",
    text: "소파에서 현관이나 화장실로 가는 길에 콘센트·선풍기·화분·낮은 탁자·택배상자 등이 놓여 있나요?",
    finding: "거실 통로에 물건이 놓여 있어요.",
    action: "물건을 치우거나 전선은 벽면을 따라 고정한다. 낮은 탁자와 화분은 통로 밖으로 옮긴다.",
    urgent: false,
  },
  {
    id: "living-support",
    zoneId: "living",
    text: "낮은 소파나 바닥에 앉았다 일어날 때 흔들리는 탁자나 가구를 붙잡나요?",
    finding: "일어날 때 흔들리는 가구를 붙잡고 있어요.",
    action: "팔걸이가 있는 단단한 의자를 배치한다. 말랑한 소파나 바퀴 달린 가구를 지지대로 사용하지 않는다.",
    urgent: true,
  },
  {
    id: "bath-slip",
    zoneId: "bath",
    text: "샤워 후 타일 바닥에 물기가 남아 있거나, 욕실화·발매트가 쉽게 미끄러지나요?",
    finding: "화장실 바닥이 젖거나 매트가 미끄러져요.",
    action: "물기는 걸레로 바로 없앤다. 바닥에 고정되는 미끄럼 방지 매트와 잘 맞는 욕실화를 사용한다.",
    urgent: true,
  },
  {
    id: "bath-grab",
    zoneId: "bath",
    text: "변기에 앉고 일어나거나 샤워 공간에 들어갈 때 수건걸이·세면대·문손잡이를 붙잡나요?",
    finding: "화장실에서 수건걸이나 세면대를 붙잡고 있어요.",
    action: "변기 옆과 샤워 공간 벽에 체중을 지지할 수 있는 고정형 안전손잡이를 전문가가 설치하도록 한다. 절대 수건걸이는 지지대로 사용하지 않는다.",
    urgent: true,
  },
  {
    id: "bath-sill",
    zoneId: "bath",
    text: "화장실 문턱이 높거나, 밤에 화장실 입구와 내부가 어두워 문턱을 알아보기 어렵나요?",
    finding: "화장실 문턱이 높거나 밤에 잘 안 보여요.",
    action: "문턱을 제거하거나 문턱에는 바닥과 구별되는 색을 표시하고, 출입구부터 내부까지 센서등을 설치한다.",
    urgent: false,
  },
  {
    id: "kitchen-reach",
    zoneId: "kitchen",
    text: "자주 사용하는 냄비·그릇을 꺼내기 위해 허리를 깊게 숙이거나 팔을 머리 위로 뻗어야 하나요?",
    finding: "부엌에서 물건을 꺼낼 때 몸을 많이 굽히거나 팔을 높이 뻗고 있어요.",
    action: "자주 사용하는 물건은 허리와 어깨 사이 높이의 수납장으로 옮긴다. 무거운 냄비는 싱크대 옆에 둔다.",
    urgent: false,
  },
  {
    id: "kitchen-climb",
    zoneId: "kitchen",
    text: "높은 수납장의 물건을 꺼내기 위해 의자나 상자 위에 올라가나요?",
    finding: "부엌에서 의자나 상자 위에 올라가고 있어요.",
    action: "의자나 상자에 올라가지 않는다. 필요한 경우 가족에게 도움을 요청한다.",
    urgent: true,
  },
  {
    id: "kitchen-wet",
    zoneId: "kitchen",
    text: "싱크대나 가스레인지 주변에 물이 떨어져 있거나, 주방매트가 자주 밀리나요?",
    finding: "부엌 바닥에 물이 있거나 매트가 밀려요.",
    action: "바닥의 물은 바로 닦는다. 헐거운 주방매트는 제거하고, 바닥에 밀림이 덜한 매트로 교체한다.",
    urgent: false,
  },
  {
    id: "bedroom-bed",
    zoneId: "bedroom",
    text: "바닥에 이불을 펴고 자거나 침대가 너무 낮아, 일어날 때 바닥·협탁·이불을 짚어야 하나요?",
    finding: "침실에서 일어날 때 바닥이나 이불을 짚고 있어요.",
    action: "가능하면 발바닥이 바닥에 닿는 높이의 침대를 사용한다. 침대 옆에는 고정된 손잡이나 팔걸이 의자를 배치한다.",
    urgent: false,
  },
  {
    id: "bedroom-clutter",
    zoneId: "bedroom",
    text: "침대 근처에 이불 끝, 옷, 휴대전화 충전선 등이 발에 걸릴 수 있게 놓여 있나요?",
    finding: "침대 근처에 발에 걸릴 물건이 있어요.",
    action: "자기 전에 침대 근처 물건과 전선을 정리한다. 땅에 끌리지 않는 사이즈의 이불을 덮는다.",
    urgent: false,
  },
  {
    id: "bedroom-light",
    zoneId: "bedroom",
    text: "침대에서 손을 뻗어 조명을 켤 수 없거나, 안경, 지팡이, 휴대전화를 찾으려고 어두운 상태에서 일어나야 하나요?",
    finding: "침실에서 어두운 채로 일어나 물건을 찾고 있어요.",
    action: "손이 닿는 곳에 조명과 안경, 보행보조기, 휴대전화를 둔다. 침대 옆에 동작 감지등을 설치한다.",
    urgent: false,
  },
  {
    id: "path-dark",
    zoneId: "path",
    text: "밤에 침실에서 화장실까지 가는 길이 어둡거나, 조명을 켜기 전에 걸어가야 하나요?",
    finding: "밤에 침실에서 화장실까지 가는 길이 어두워요.",
    action: "침대 옆부터 복도·화장실 입구까지 연속적으로 켜지는 센서등이나 야간조명을 설치한다. 침대 옆에 손전등도 둔다.",
    urgent: true,
  },
  {
    id: "path-trip",
    zoneId: "path",
    text: "이동경로에 이불이나 전선, 문턱, 가구 모서리 등 걸리거나 부딪힐 것이 있나요?",
    finding: "침실-화장실 길에 걸리거나 부딪힐 것이 있어요.",
    action: "침대에서 화장실까지 폭이 일정한 직선 통로를 확보한다. 전선과 물건을 치우고, 가구는 문쪽과 멀리 이동한다.",
    urgent: true,
  },
  {
    id: "path-support",
    zoneId: "path",
    text: "화장실까지 이동하면서 벽·문짝·서랍장처럼 체중을 지지하기 어려운 물체를 붙잡아야 하나요?",
    finding: "화장실로 가면서 벽이나 가구를 붙잡고 있어요.",
    action: "필요한 구간에는 고정형 손잡이를 설치한다. 보행보조기는 침대 옆에서 바로 사용할 수 있게 두고, 미끄러운 양말 대신 뒤꿈치가 고정되는 미끄럼 방지 양말을 신는다.",
    urgent: true,
  },
  {
    id: "entrance-clutter",
    zoneId: "entrance",
    text: "현관 바닥에 신발이나 택배상자·장바구니 같은 물건들이 놓여 발 디딜 공간이 부족한가요?",
    finding: "현관에 신발과 물건이 많아 발 디딜 공간이 부족해요.",
    action: "자주 신는 신발 한두 켤레만 남기고 신발장에 정리한다. 택배와 우산은 현관이 아닌 장소에 둔다.",
    urgent: false,
  },
  {
    id: "entrance-step",
    zoneId: "entrance",
    text: "현관과 실내 바닥 사이의 단차가 크거나, 둘의 바닥 색이 비슷해서 잘 보이지 않나요?",
    finding: "현관 단차가 크거나 바닥 색이 비슷해 잘 안 보여요.",
    action: "단차 사이에 밝고 구별되는 색의 미끄럼 방지 표시를 붙이고, 바닥 조명을 설치한다.",
    urgent: false,
  },
  {
    id: "entrance-chair",
    zoneId: "entrance",
    text: "신발을 서서 신거나 벗으면서 벽·신발장 문 등을 붙잡나요?",
    finding: "현관에서 신발을 신을 때 벽이나 문을 붙잡고 있어요.",
    action: "등받이와 팔걸이가 있고 흔들리지 않는 의자를 놓는다.",
    urgent: false,
  },
];

export const RESULT_BANDS = [
  {
    id: "clear",
    title: "이번 점검에서 확인된 환경 개선 항목이 없습니다",
    body: "지금은 큰 위험 요소가 보이지 않습니다. 잘 모르겠어요로 남긴 곳이 있다면 가족과 한번 더 살펴봐 주세요.",
  },
  {
    id: "check",
    title: "일부 항목을 확인해 주세요",
    body: "이 공간에서 우선 확인할 환경 항목이 있습니다. 아래 안내부터 천천히 바꿔 보세요.",
  },
  {
    id: "several",
    title: "여러 항목의 개선이 필요합니다",
    body: "집 안의 여러 곳에서 넘어지기 쉬운 환경이 확인되었습니다. 먼저 고칠 곳부터 정리해 보세요.",
  },
  {
    id: "priority",
    title: "우선 조치가 필요한 항목이 있습니다",
    body: "바로 손볼 환경 항목이 있습니다. 의료 진단이 아니라, 집에서 먼저 확인할 개선 안내입니다.",
  },
];

export const HEALTH_TIPS = [
  {
    id: "what-is-fall",
    tag: "낙상이 뭘까?",
    title: "낙상은 예방할 수 있는 건강문제입니다",
    subtitle: "작은 넘어짐도 골절과 활동 저하로 이어질 수 있어요",
    image: "news-1.png",
    paragraphs: [
      "낙상은 사람이 의도치 않게 땅이나 바닥 또는 더 낮은 곳에 넘어지는 사건입니다. 낙상으로 인한 부상은 치명적일 수도 있고 비치명적일 수도 있습니다.",
      "WHO(세계보건기구)에 따르면 매년 전 세계에서 약 68만 4천 건의 치명적인 낙상 사고가 발생합니다. 치료가 필요할 정도로 심한 낙상은 매년 약 3,730만 건 발생합니다.",
      "특히 65세 이상은 치명적인 낙상을 가장 많이 경험하는 연령층입니다.",
      "낙상은 고관절 골절이나 머리 손상뿐 아니라 걷는 것에 대한 두려움도 남깁니다. 그 결과 움직임이 줄고 근력이 약해져 다시 넘어질 위험이 커질 수 있습니다.",
      "바닥의 물건을 치우고 조명을 밝히는 작은 변화부터 시작해 보세요. 낙상은 운이 나빠서 생기는 사고가 아니라, 미리 발견하고 줄일 수 있는 위험입니다.",
    ],
    source: "질병관리청",
  },
  {
    id: "ten-minutes-home",
    tag: "안전한 우리집",
    title: "우리집, 낙상 위험으로부터 안전하게 가꾸어요",
    subtitle: "물기·문턱·전선·깔개·어두운 조명을 확인하세요",
    image: "news-2.jpg",
    paragraphs: [
      "화장실 타일과 거실 장판에 남은 물기는 발견하는 즉시 닦아주세요. 싱크대 주변의 물과 기름도 미끄러짐의 원인이 될 수 있습니다.",
      "들뜨거나 밀리는 발매트와 러그는 제거하거나 바닥에 단단히 고정하세요. 전선·신발·택배상자는 침실에서 화장실까지의 통로 밖으로 옮겨주세요.",
      "화장실과 계단에는 고정형 안전손잡이를 설치하는 것이 좋습니다. 어두운 복도와 높은 문턱에는 센서등과 눈에 잘 띄는 표시를 더해주세요.",
      "오늘 한 공간만 점검해도 내일의 낙상 위험을 줄일 수 있습니다.",
    ],
    source: "질병관리청",
  },
  {
    id: "leg-strength",
    tag: "하체 건강",
    title: "넘어지지 않는 하루는 나의 튼튼한 하체에서 시작!",
    subtitle: "무리하지 말고 일주일에 2~3회 꾸준히 해보세요",
    image: "news-3.png",
    paragraphs: [
      "나이가 들면 근육량과 다리 힘이 감소해 걷거나 일어서기가 어려워질 수 있습니다. 또 근력이 약해지고 균형이 떨어지면 작은 문턱에도 쉽게 넘어질 수 있습니다.",
      "질병관리청은 낙상 예방을 위한 근력운동을 주 2~3회 권장합니다. 안정된 의자를 잡고 앉았다 일어나기와 발뒤꿈치 들기부터 시작해 보세요.",
      "운동 전후에는 종아리·허벅지·허리 근육을 천천히 풀어주는 것이 좋습니다. 다만 어지럽거나 통증이 생기면 즉시 멈추고 의료진과 상담하세요.",
      "중요한 것은 강도 높은 운동이 아니라, 집에서 할 수 있는 안전하고 지속적인 운동입니다.",
    ],
    source: "질병관리청",
  },
  {
    id: "osteoporosis",
    tag: "골다공증",
    title: "나의 다리, 골다공증과 골절 위험",
    subtitle: "뼈가 약하면 가벼운 낙상도 큰 골절이 될 수 있어요",
    image: "news-4.jpg",
    paragraphs: [
      "골다공증은 뼈의 강도가 약해져 작은 충격에도 쉽게 골절되는 질환입니다. 국민건강영양조사 2008~2011년 자료에서 50세 이상 골다공증 유병률은 여성 37.3%, 남성 7.5%였습니다.",
      "또한 50세 이상 성인의 약 47.9%에서 골감소증이 확인된 분석도 있습니다. 골다공증은 증상이 거의 없어 골절이 발생한 뒤 발견되는 경우가 있습니다.",
      "칼슘·비타민 D 섭취, 근력운동, 금연과 절주, 낙상 예방이 중요합니다. 폐경 이후 여성이나 이전에 골절을 경험한 사람은 골밀도검사 필요성을 상담해 보세요.",
      "뼈를 튼튼하게 관리하는 일과 넘어지지 않는 환경을 만드는 일은 함께해야 합니다.",
    ],
    source: "질병관리청",
  },
  {
    id: "dizziness",
    tag: "어지럼",
    title: "자리에서 일어나면 겪는 어지럼과 약물 교육",
    subtitle: "어지럼은 낙상이 보내는 중요한 경고신호입니다",
    image: "news-5.png",
    paragraphs: [
      "누워 있거나 앉아 있다가 갑자기 일어나면 혈압이 떨어져 어지러울 수 있습니다. 이러한 기립성 어지럼은 균형을 잃거나 실신해 넘어지는 원인이 됩니다.",
      "일어나기 전 침대 가장자리에 앉아 1~2분 기다린 뒤 천천히 움직이세요.",
      "혈압약·전립선질환 약·신경통 관련 약물 등도 어지럼을 유발할 수 있습니다. 약을 임의로 끊지 말고, 복용 후 어지럼이 반복되면 의사나 약사에게 알려주세요.",
      "혹여 말이 어눌해지거나 한쪽 팔다리에 힘이 빠지는 어지럼은 즉시 진료가 필요합니다.",
      "몸이 보내는 ‘핑 도는 신호’를 무시하지 않는 것이 낙상 예방의 시작입니다.",
    ],
    source: "질병관리청",
  },
];
